import {HOST} from "./host";
export const MASTER_JSON_MESSAGES={
    MASTER_JSON_PAGE_TITLE:"Add Master Json Data",
    MASTER_JSON_PAGE_PROMPT_MSG_ON_DUPLICATE_ORDERID:"Order ID Already Exists \n Wish to change order ID",
    MASTER_JSON_PAGE_STORAGE_ORDERID_KEY:"orderID",
    MASTER_JSON_PAGE_ERROR_404:"NOT FOUND",
    MASTER_JSON_PAGE_ERROR_500:"INTERNAL SERVER ERROR",
    MASTER_JSON_PAGE_ORDERID_UNDEFINED_ERROR:"Required OrderId*.\n NOT FOUND",
    MASTER_JSON_PAGE_POST_SUCCESSFUL:"Added to Master Successfully",
    MASTER_JSON_PAGE_ADD_MASTER_API_URL:"http://"+HOST.URL+":"+HOST.PORT+"/Master/AddMaster",
    MASTER_JSON_PAGE_POST_BUTTON:"ADD"

}