export const NAVIGATION_MESSAGES={
    NAVIGATION_BAR_TO_DATA_PAGE:"DATA",
    NAVIGATION_BAR_TO_MAPPING_PAGE:"MAPPING",
    NAVIGATION_BAR_TO_ADD_MASTER_PAGE:"ADD MASTER",
    NAVIGATION_BAR_LOGOUT:"LOG OUT",
    NAVIGATION_BAR_MAPPING_PAGE_TITLE:"CUSTOMIZE MAPPINGS",
    NAVIGATION_BAR_DATA_PAGE_TITLE:"MAPPED MASTER DATA",
    NAVIGATION_BAR_ADD_MASTER_PAGE_TITLE:"CUSTOMIZE MASTER DATA"

}