import {HOST} from "./host";
export const MASTER_MAPPING_MESSAGES={
    MASTER_MAPPING_PAGE_TITLE:"MAP MASTER DATA",
    MASTER_MAPPING_PAGE_MASTER_INPUT_LABEL:"Enter Master Order ID :",
    MASTER_MAPPING_PAGE_MAP_BUTTON:"MAP MASTER",
    MASTER_MAPPING_PAGE_MASTER_BUTTON:"MASTER JSON",
    MASTER_MAPPING_PAGE_INIT_MESSAGE:" ",
    MASTER_MAPPING_PAGE_SESSION_STORAGE_KEY:"userId",
    MASTER_MAPPING_PAGE_MAP_MASTER_API_URL:"http://"+HOST.URL+":"+HOST.PORT+"/userMappings/mapOrdersToMappings/",
    MASTER_MAPPING_PAGE_MASTER_DATA_API_URL:"http://"+HOST.URL+":"+HOST.PORT+"/Master/FindMaster/",
    MASTER_MAPPING_PAGE_ERROR_404:"NOT FOUND",
    MASTER_MAPPING_PAGE_ERROR_403:"Unauthorized Request",
    MASTER_MAPPING_PAGE_ERROR_500:"INTERNAL SERVER ERROR"

}